### ISSUE TITLE
Cloud Setup

### ISSUE THREAD

**Issue by vipin-singh1** [keyban/fogframe#3]
Hi, I am using your fogframe implementation for a project. I have successfully deployed the fog environment and am able to send fog tasks to the raspberry pis. I would like to know how to set up the OpenStack cloud with the fogframe, is there any tutorials available that would prove to be helpful for the same. Any help would be appreciated.

Thanks

**Comment by softls** [comment]
Connector to the cloud is implemented in cloud fog middleware. It is done though the openstack api java library, in the pom of the cloud fog middleware you can find all of them and look at them. https://developer.openstack.org/draft/firstapp-jclouds/getting_started.html
In cloud-fog middleware in the resources/docker-config, cloud-init file describes which kind of vm should be started on the cloud. In the resources/cloud there is a file credential.properties. This file has to be filled in with account data from the cloud provider. credential.sample.properties contains a stab which needs to be filled in. In the cloud provider, i use one AMI image i created with docker enabled, CentOS, you may try with other operation systems, create one image with docker setup. Security group in the cloud provider should open all necessary ports. Also, detailed descriptions are provided in Section 5.4.2 in http://www.infosys.tuwien.ac.at/staff/sschulte/paper/Bachmann_Master.pdf
